name: watch_with_me
description: "A streaming app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  http: ^1.2.0
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.2.2
  awesome_snackbar_content: ^0.1.3
  flutter_launcher_icons: ^0.13.1
  after_layout: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/playstore.png"
  image_path_ios: "assets/appstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "assets/backgroundLogoColor.png"
  adaptive_icon_foreground: "assets/playstore.png"
  background_color_ios: "#F6F9F8"



flutter:
  uses-material-design: true

  assets:
    - assets/watchWithMeLogo.png
    - assets/facebook_logo.png
    - assets/gmail_logo.png
    - assets/doneIcon.png

  fonts:
    - family: Chalet
      fonts:
        - asset: custom_fonts/fonts/chalet.ttf
    - family: Montserrat
      fonts:
        - asset: custom_fonts/fonts/montserrat.ttf
  
