name: watch_with_me
description: "A streaming app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  font_awesome_flutter: ^10.6.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/watchWithMeLogo.png
    - assets/facebook_logo.png
    - assets/gmail_logo.png
    - assets/doneIcon.png

  fonts:
    - family: Chalet
      fonts:
        - asset: custom_fonts/fonts/chalet.ttf
    - family: Montserrat
      fonts:
        - asset: custom_fonts/fonts/montserrat.ttf
  
